merge request
mgacrama211176/katiwala pull request #9
Opened 2024-01-18 10:36 UTC by marlonosia

please check and merge my request

2024-01-18 10:54 UTC, mgacrama211176 requested changes
Good Job but refer on docs for correct structure building.

2024-01-18 10:54 UTC, mgacrama211176 commented on screens/Register/index.jsx
>   import { SafeAreaView } from "react-native-safe-area-context";
Meron na to sa react-native. 

You just need to call the element SafeAreaView.
https://reactnative.dev/docs/safeareaview

2024-01-18 10:54 UTC, mgacrama211176 commented on screens/Register/index.jsx
>   const Register = ({ navigation,phone }) => {
San to galing si phone?

This is not needed.

2024-01-18 10:54 UTC, mgacrama211176 commented on screens/Register/index.jsx
> +                value={value}
You are placing value to a non-existent value. 

Either you manually put a default value or use a UseState method to store your value.

https://www.w3schools.com/react/react_usestate.asp

2024-01-18 10:54 UTC, mgacrama211176 commented on screens/Register/index.jsx
>                }} />
Incorrect usage of the image element:

https://reactnative.dev/docs/image

2024-01-18 10:54 UTC, mgacrama211176 commented on screens/Register/index.jsx
For the textInput there is a way for the default input data to always stay on lowerCase or upperCase:

https://reactnative.dev/docs/text-style-props#texttransform

2024-01-18 10:54 UTC, mgacrama211176 commented on screens/Register/index.jsx
For email text Input Check docs for auto checking if the inputed data is an email:

https://reactnative.dev/docs/textinput

2024-01-18 10:54 UTC, mgacrama211176 commented on screens/Register/index.jsx
Skills Offered should be Select Element not TextInput

2024-01-18 11:04 UTC, marlonosia commented on screens/Register/index.jsx
>   const Register = ({ navigation,phone }) => {
okay sir I remove

2024-01-27 05:13 UTC, mgacrama211176 requested changes
Almost there. Good Job. Errors trappings na next.

2024-01-27 05:13 UTC, mgacrama211176 commented on screens/Register/index.jsx
> +  onPress,
remove unused imports

2024-01-27 05:13 UTC, mgacrama211176 commented on screens/Register/index.jsx
> +    ];
options can be directly called on line#53

2024-01-27 05:13 UTC, mgacrama211176 commented on screens/Register/index.jsx
> +
Remove some of the excess spacings.

2024-01-27 07:36 UTC, marlonosia commented on screens/Register/index.jsx
> +
okay

2024-01-28 04:35 UTC, mgacrama211176 requested changes
Almost Done. Just make sure to apply all the onChangeText to make sure that we have stored the data.

2024-01-28 04:35 UTC, mgacrama211176 commented on screens/Register/index.jsx
> +  const [verifyPassword, setVerifyPassword] = useState(""); //checker if the password and verify password is correct
Remove unsused variables.

2024-01-28 04:35 UTC, mgacrama211176 commented on screens/Register/index.jsx
> +            <TextInput
OnchangeText change missing. After Input what will happen to the inputted data if not stored.

2024-01-28 04:35 UTC, mgacrama211176 commented on screens/Register/index.jsx
> +            />
Need to make sure that the TextInput only accepts email. Needs validation.

2024-01-28 04:35 UTC, mgacrama211176 commented on screens/Register/index.jsx
> +            />
This needs to be a datepicker not a textInput

2024-01-28 04:35 UTC, mgacrama211176 commented on screens/Register/index.jsx
> +  };
Add an error trapping where if the verifypassword is empty there should be no error message.

2024-01-28 04:36 UTC, mgacrama211176 requested changes
Almost Done. Just make sure to apply all the onChangeText to make sure that we have stored the data.

2024-02-06 12:03 UTC, stolenfallen1 approved these changes
If @mgacrama211176 request are done, can merge :)

2024-02-10 06:04 UTC, mgacrama211176 approved these changes
Good Job on doing the tasks there are still a couple of issues but the main functionality for registration is working.

Need to work on:

1. Password verification.
2. Date of Birth bug when pressed.
3. Email Verification.

This can now be merged but please check issues for immediate fix.

2024-02-12 14:34 UTC, merged